DROP DATABASE IF EXISTS GETMORE;
CREATE DATABASE GETMORE;

DROP USER IF EXISTS getmore;
CREATE USER getmore WITH PASSWORD 'nodejsbackend';
GRANT ALL PRIVILEGES ON GETMORE TO getmore;

DROP TABLE IF EXISTS categories;

CREATE TABLE categories(
	id SMALLINT PRIMARY KEY,
	name VARCHAR(250) NOT NULL UNIQUE,
	parent_id SMALLINT REFERENCES categories(id)
);

DROP INDEX IF EXISTS name_index;
CREATE INDEX name_index ON categories(name);